version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server
    ports:
      - "5000:5000"
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"